services:
  database:
    image: mysql:latest
    container_name: mysql-container
    volumes:
      - db-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=root
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
volumes:
  db-volume: